[Icon Theme]
Name=Nothing
Comment=Nothing OS - white glyphs on dark squircles
Inherits=hicolor
DisplayDepth=32
Example=folder
FollowsColorScheme=false

DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256

Directories=scalable/apps,scalable/places,128/apps,128/places,128/mimetypes,22/actions

[scalable/apps]
Size=128
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[128/apps]
Size=128
Context=Applications
Type=Fixed

[scalable/places]
Size=128
Context=Places
Type=Scalable
MinSize=16
MaxSize=256

[128/places]
Size=128
Context=Places
Type=Scalable
MinSize=16
MaxSize=256

[128/mimetypes]
Size=128
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=256

[22/actions]
Size=22
Context=Actions
Type=Fixed
