#!/usr/bin/env bash
# Add "Nothing" to SDDM's session list, and install the greeter theme
# used by this rice (sddm-astronaut-theme, Hyprland Kath).
#
#   sudo ./scripts/install-session.sh
#   sudo ./scripts/install-session.sh --remove
#
# Note: SDDM runs as the "sddm" user BEFORE login. If home is
# 0710 (the default on many installs), it cannot walk /home/<user>
# and a TryExec pointing in there makes the entry vanish silently.
# The launcher is therefore placed in /usr/local/bin, readable by
# everyone; it only calls the repo after login, as you.
set -euo pipefail

ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)"
OWNER="$(stat -c '%U' "$ROOT")"
LAUNCHER=/usr/local/bin/nothing-session
DESKTOP=/usr/share/wayland-sessions/nothing.desktop
THEME_DIR=/usr/share/sddm/themes/sddm-astronaut-theme
THEME_GIT=https://github.com/keyitdev/sddm-astronaut-theme.git
THEME_CONF=Themes/hyprland_kath.conf
SDDM_DROPIN=/etc/sddm.conf.d/10-nothing.conf

if [[ $EUID -ne 0 ]]; then
    echo "Root privileges required: sudo $0 $*" >&2
    exit 1
fi

if [[ "${1:-}" == "--remove" ]]; then
    rm -f "$DESKTOP" "$LAUNCHER" "$SDDM_DROPIN"
    echo "Removed: $DESKTOP"
    echo "Removed: $LAUNCHER"
    echo "Removed: $SDDM_DROPIN"
    echo "Left in place: $THEME_DIR (the greeter theme)"
    exit 0
fi

clone_theme() {
    mkdir -p "$(dirname "$THEME_DIR")"
    rm -rf "$THEME_DIR"
    # stdin must not be a consumed sudo -S pipe: git checkout then
    # writes 0-byte files (Main.qml empty → SDDM refuses the theme).
    git clone --depth 1 -b master "$THEME_GIT" "$THEME_DIR" </dev/null
}

theme_ok() {
    [[ -s "$THEME_DIR/Main.qml" && -s "$THEME_DIR/$THEME_CONF" ]]
}

install_theme() {
    echo "Greeter  : sddm-astronaut-theme ($THEME_CONF)"
    if ! theme_ok; then
        if [[ -d "$THEME_DIR/.git" ]]; then
            git -C "$THEME_DIR" reset --hard HEAD </dev/null || true
        fi
    fi
    if ! theme_ok; then
        clone_theme
    fi
    if ! theme_ok; then
        echo "  FAIL: Main.qml is missing or empty at $THEME_DIR" >&2
        return 1
    fi
    sed -i "s|^ConfigFile=.*|ConfigFile=$THEME_CONF|" "$THEME_DIR/metadata.desktop"
    # Theme ships a virtual-keyboard toggle; keep it off.
    sed -i 's/^HideVirtualKeyboard=.*/HideVirtualKeyboard="true"/' \
        "$THEME_DIR/$THEME_CONF" || true
    if [[ -d "$THEME_DIR/Fonts" ]]; then
        mkdir -p /usr/share/fonts/sddm-astronaut
        cp -a "$THEME_DIR/Fonts"/. /usr/share/fonts/sddm-astronaut/
        fc-cache -f >/dev/null 2>&1 || true
    fi
    install -d /etc/sddm.conf.d
    # printf, not a heredoc: `sudo -S` leaves stdin empty and has
    # already eaten a previous attempt's drop-in on some machines.
    # Do not set InputMethod=qtvirtualkeyboard: that forces the
    # on-screen keyboard on the fallback greeter too.
    printf '%s\n' \
        '[Theme]' \
        'Current=sddm-astronaut-theme' \
        '' \
        '[General]' \
        'InputMethod=' \
        > "$SDDM_DROPIN"
    printf '%s\n' \
        '[Theme]' \
        'Current=sddm-astronaut-theme' \
        > /etc/sddm.conf
    chmod 644 "$SDDM_DROPIN" /etc/sddm.conf
    if [[ ! -s "$SDDM_DROPIN" ]]; then
        echo "  FAIL: $SDDM_DROPIN is empty" >&2
        return 1
    fi
    echo "Config   : $SDDM_DROPIN"
}

install -d /usr/local/bin

cat > "$LAUNCHER" <<LAUNCH
#!/usr/bin/env bash
# Generated by hypr_nothing/scripts/install-session.sh - do not edit.
exec "$ROOT/scripts/nothing-session.sh" "\$@"
LAUNCH
chmod 755 "$LAUNCHER"
echo "Launcher : $LAUNCHER"

cat > "$DESKTOP" <<DESK
[Desktop Entry]
Name=Nothing
Comment=Hyprland + Quickshell, Nothing OS theme
Exec=$LAUNCHER
TryExec=$LAUNCHER
Type=Application
DesktopNames=Hyprland
Keywords=tiling;wayland;compositor;nothing;
DESK
chmod 644 "$DESKTOP"
echo "Session  : $DESKTOP"

install_theme

# Check: can the sddm user actually reach all of this?
echo
echo "Access check from the sddm user:"
if id sddm >/dev/null 2>&1; then
    if setpriv --reuid=sddm --regid=sddm --clear-groups \
            test -x "$LAUNCHER" 2>/dev/null; then
        echo "  OK  $LAUNCHER is executable by sddm"
    else
        echo "  FAIL: sddm cannot execute $LAUNCHER"
    fi
    if setpriv --reuid=sddm --regid=sddm --clear-groups \
            test -r "$DESKTOP" 2>/dev/null; then
        echo "  OK  $DESKTOP is readable by sddm"
    else
        echo "  FAIL: sddm cannot read $DESKTOP"
    fi
    if setpriv --reuid=sddm --regid=sddm --clear-groups \
            test -r "$THEME_DIR/Main.qml" 2>/dev/null; then
        echo "  OK  greeter theme is readable by sddm"
    else
        echo "  FAIL: sddm cannot read $THEME_DIR"
    fi
    if setpriv --reuid=sddm --regid=sddm --clear-groups \
            test -x "$ROOT/scripts/nothing-session.sh" 2>/dev/null; then
        echo "  info  the repo is also readable by sddm (not required)"
    else
        echo "  info  the repo is not readable by sddm - expected, and"
        echo "        harmless: the launcher only uses it after login,"
        echo "        as $OWNER."
    fi
else
    echo "  sddm user not found, check skipped"
fi

cat <<MSG

Done. Log out, then open SDDM's session picker and choose "Nothing".

The greeter is sddm-astronaut-theme (Hyprland Kath). The picker is a
small icon or drop-down, often at the bottom or top of the screen.
If it still shows the old look, reboot once, or:

    sudo rm -f /var/lib/sddm/state.conf

To remove: sudo $0 --remove
MSG
